### ISSUE TITLE
DeprecationWarning + cannot deploy

### ISSUE THREAD

**Issue by andraghetti** [udugama/serverless-s3-inventory-report#1]
Hi, thank you for the plugin. It's very useful, but unfortunately it doesn't work anymore.

Sadly I don't know how to fix it myself. I understand that it's very old, but maybe you could show me how to fix it and I could open a PR here.

I get this error, going [here](https://www.npmjs.com/package/serverless-s3-inventory-report) and clicking on "Try on runkit".

```
(node:1) [DEP0128] DeprecationWarning: Invalid 'main' field in '/app/available_modules/1663859903000/serverless-s3-inventory-report/package.json' of 'dist/index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
```

On my computer I have the following environment: `darwin, node 18.6.0, framework 3.22.0 (local) 3.22.0v (global), plugin 6.2.2, SDK 4.3.2` and I get:

```
Error:
TypeError: Cannot read properties of undefined (reading 'Id')
    at ReportConfigurator.<anonymous> (/home/me/node_modules/serverless-s3-inventory-report/inventory/ReportConfigurator.js:39:55)
    at Generator.next (<anonymous>)
    at fulfilled (/home/me/node_modules/serverless-s3-inventory-report/inventory/ReportConfigurator.js:4:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

1 deprecation found: run 'serverless doctor' for more details

```

**Comment by andraghetti** [comment]
I just realized that the error comes out from trying to have multiple configurations. So now I was wondering, is there a way to have multiple configurations? I would like to create an inventory for different buckets.

Thank you so much!

**Comment by udugama** [comment]
Hi mate, glad to hear you are using it let me have a look and address the
issue ..
Regards
Prasad
